# Lazy jobs running on master post merges.
name: lazy
on:
  push:
    branches: [master]

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Generate report
        uses: actions-rs/tarpaulin@v0.1
        with:
          args: '--tests --all-features --workspace'
      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Archive code coverage results
        uses: actions/upload-artifact@v1
        with:
          name: code-coverage-report
          path: cobertura.xml
  parse-dota2:
    name: Parse Dota2 shaders
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - run: mkdir data
      - name: Download shaders
        run: curl https://user.fm/files/v2-5573e18b9f03f42c6ae53c392083da35/dota2-shaders.zip -o data/all.zip
      - name: Unpack shaders
        run: cd data && unzip all.zip
      - name: Build Naga
        run: cargo build --release --bin naga
      - name: Convert shaders
        run: for file in data/*.spv ; do echo "Translating" ${file} && target/release/naga --validate 27 ${file} ${file}.metal; done
  parse-vulkan-tutorial-shaders:
    name: Parse Sascha Willems Vulkan tutorial shaders
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Download shaders
        run: git clone https://github.com/SaschaWillems/Vulkan.git
      - name: Build Naga
        run: cargo build --release --bin naga
      - name: Convert metal shaders
        run: |
          # No needed to stop workflow if we can't validate one file
          set +e
          touch counter
          SUCCESS_RESULT_COUNT=0
          FILE_COUNT=0
          mkdir -p out
          find "Vulkan/data/shaders/glsl/" -name '*.spv' | while read fname;
          do
              echo "Convert: $fname"
              FILE_COUNT=$((FILE_COUNT+1))
              target/release/naga --validate 27 $(realpath ${fname}) out/$(basename ${fname}).metal
              if [[ $? -eq 0 ]]; then
                  SUCCESS_RESULT_COUNT=$((SUCCESS_RESULT_COUNT + 1))
              fi
              echo "Result: $(expr $FILE_COUNT - $SUCCESS_RESULT_COUNT) / $FILE_COUNT" > counter
          done
          cat counter
